spring:
  application:
    name: retry

  cloud:
    stream:
      bindings:
        genericMessageConsumer-in-0:
          destination: topic-1
          group: group-1
          consumer:
            maxAtttempts: 3
            backOffInitialInterval: 2000
            backOffMultipler: 2
            backOffMaxInterval: 20000
      kafka:
        binder:
          brokers:
            - http://localhost:29092
          replicationFactor: 1
          autoCreateTopics: true
        bindings:
          genericMessageConsumer-in-0:
            consumer:
              max.poll.interval.ms: 300000
              enableDlq: true
              dlqName: topic-1-dlt
