spring:
  application:
    name: retry

  cloud:
    config:
      enabled: true
      uri: http://localhost:9092
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
          replicationFactor: 1
          autoCreateTopics: true
        bindings:
          genericMessageConsumer-in-0:
            destination: topic-1
            content-type: application/json
            group: group-1
